server/accounts/urls.py
from django.urls import path
from .views import ProfileListView, LoginView, RegisterUserCreateView, StudyGroupListView, StudyGroupCreateView, \
    StudyGroupUpdateView, StudyGroupDeleteView, GroupStudentListView, StudentResultListView, ProfileUpdateView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('profile/', ProfileListView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update_profile'),

    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterUserCreateView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='main:home'), name='logout'),

    path('group/list/', StudyGroupListView.as_view(), name='group_list'),
    path('group/create/', StudyGroupCreateView.as_view(), name='create_group'),
    path('group/<slug:pk>/update/', StudyGroupUpdateView.as_view(), name='update_group'),
    path('group/<slug:pk>/delete/', StudyGroupDeleteView.as_view(), name='delete_group'),
    path('group/<slug:pk>/student/list/', GroupStudentListView.as_view(), name='group_student_list'),

    path('student/<slug:pk>/result/list/', StudentResultListView.as_view(), name='student_result_list'),


]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/main/urls.py
from django.urls import path
from .views import TestCreateView, TestListView, QuestionListView, QuestionCreateView, QuestionUpdateView, \
    QuestionDeleteView, TestDetailView, TestUpdateView, TestDeleteView, PassingTestView, ResultDetailView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    #  Main Page
    path('', TestListView.as_view(), name='home'),
    #  Test CRUD Urls
    path('test/create/', TestCreateView.as_view(), name='create_test'),
    path('test/<slug:pk>/update/', TestUpdateView.as_view(), name='update_test'),
    path('test/<slug:pk>/delete/', TestDeleteView.as_view(), name='delete_test'),
    path('test/<slug:pk>/about/', TestDetailView.as_view(), name='about_test'),
    path('test/<slug:pk>/pass/', PassingTestView.as_view(), name='pass_test'),
    path('result/<slug:pk>/info/', ResultDetailView.as_view(), name='test_result'),
    #  Question Urls
    path('test/<slug:test_id>/quest/list/', QuestionListView.as_view(), name='quest_list'),
    path('test/<slug:test_id>/quest/create/', QuestionCreateView.as_view(), name='create_quest'),
    path('test/<slug:test_id>/quest/<slug:pk>/update/', QuestionUpdateView.as_view(), name='update_quest'),
    path('test/<slug:test_id>/quest/<slug:pk>/delete/', QuestionDeleteView.as_view(), name='delete_quest'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class StudyGroup(BaseModel):
    name = models.CharField(max_length=50, verbose_name='Название')

    class Meta:
        verbose_name_plural = 'Учебные группы'
        verbose_name = ' Учебная группа'
        ordering = ['id']

    def __str__(self):
        return f'{self.name}'


class AdvancedUser(AbstractUser):
    """
    Данный класс расширяет поля класса 'AbstractUser'.
    """
    about_user = models.CharField(max_length=128, blank=True, verbose_name="О пользователе")
    image = models.ImageField(null=True, blank=True, verbose_name='Фотография')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=50, blank=True, verbose_name='Отчество')
    group_id = models.ForeignKey(StudyGroup, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Группа')

    class Meta(AbstractUser.Meta):
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return f'{self.username}'
        # return f'{self.last_name} {self.first_name}'

server/accounts/forms.py
from django import forms
from .models import AdvancedUser, StudyGroup


class LoginForm(forms.ModelForm):
    """
    Форма авторизации.
    """
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not AdvancedUser.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с ником {username} не найден в системе.')
        user = AdvancedUser.objects.filter(username=username).first()
        if not user.check_password(password):
            raise forms.ValidationError("Неверный пароль")
        return self.cleaned_data

    class Meta:
        model = AdvancedUser
        fields = ['username', 'password']


class RegisterForm(forms.ModelForm):
    """
    Форма регистрации.
    """
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    patronymic = forms.CharField(required=False, max_length=50)
    image = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердить пароль'
        self.fields['email'].label = 'Электронная почта'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['patronymic'].label = 'Отчество'
        self.fields['image'].label = 'Аватарка'

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = AdvancedUser
        fields = ['username', 'password', 'confirm_password', 'email', 'first_name', 'last_name', 'patronymic', 'image']


class StudyGroupModelForm(forms.ModelForm):
    """
    Форма для CRUD-операция с моделью StudyGroup.
    """

    class Meta:
        model = StudyGroup
        fields = '__all__'


class AdvancedUserModelForm(forms.ModelForm):
    """
    Форма для CRUD-операция с моделью AdvancedUser.
    """
    class Meta:
        model = AdvancedUser
        fields = ['username', 'last_name', 'first_name', 'patronymic', 'about_user']

server/accounts/views.py
from django.views.generic import View, UpdateView, DeleteView, CreateView, ListView, DetailView
from .models import AdvancedUser, StudyGroup
from main.models import Result
from .forms import LoginForm, RegisterForm, StudyGroupModelForm, AdvancedUserModelForm
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@method_decorator(login_required, name='dispatch')
class ProfileListView(ListView):
    """
    View для отображения профиля пользователя
    """
    # Сделать так, чтобы только сам пользователь мог зайти в свой профиль.
    model = AdvancedUser
    template_name = "accounts/profile.html"
    context_object_name = "user_info"
    # query_pk_and_slug = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Профиль'
        context['heading'] = 'Профиль'
        return context

    def get_queryset(self):
        return AdvancedUser.objects.filter(id=self.request.user.id).first()


@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(UpdateView):
    model = AdvancedUser
    template_name = 'main/form-template.html'
    form_class = AdvancedUserModelForm
    # query_pk_and_slug = True

    def get_object(self, queryset=None):
        return AdvancedUser.objects.get(pk=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Обновить информацию о пользователе'
        context['heading'] = 'Обновить информацию о пользователе'
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('accounts:profile')


class LoginView(View):
    """
    View для авторизации пользователя.
    """
    def get(self, request):
        form = LoginForm(self.request.POST or None)
        context = {'form': form, 'title': 'Войти', 'heading': 'Войти'}
        return render(request, 'main/form-template.html', context)

    def post(self, request):
        form = LoginForm(self.request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse('main:home'))
        context = {'form': form, 'title': 'Войти', 'heading': 'Войти'}
        return render(request, 'main/form-template.html', context)


class RegisterUserCreateView(CreateView):
    """
    View для регистрации пользователя.
    """
    model = AdvancedUser
    template_name = 'main/form-template.html'
    form_class = RegisterForm
    query_pk_and_slug = True

    def get_success_url(self):
        return reverse_lazy('main:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        context['heading'] = 'Зарегистрироваться'
        return context


class StudyGroupListView(ListView):
    """
    View для списка групп.
    """
    paginate_by = 6
    model = StudyGroup
    template_name = "accounts/group-list.html"
    context_object_name = "group_info"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ''
        context['title'] = 'Все группы'
        context['heading'] = 'Все группы'
        return context


class StudyGroupCreateView(CreateView):
    """
    View для создания группы.
    """
    model = StudyGroup
    template_name = 'main/form-template.html'
    form_class = StudyGroupModelForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создать группу'
        context['heading'] = 'Создать группу'
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('accounts:group_list')


class StudyGroupUpdateView(UpdateView):
    """
    View для обновления информации о группе.
    """
    model = StudyGroup
    template_name = 'main/form-template.html'
    form_class = StudyGroupModelForm
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Обновить информацию о группе'
        context['heading'] = 'Обновить информацию о группе'
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('accounts:group_list')


class StudyGroupDeleteView(DeleteView):
    """
    View для удаления группы.
    """
    model = StudyGroup
    template_name = 'accounts/group-delete.html'
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удалить группу'
        context['heading'] = 'Удаление группы'
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('accounts:group_list')


class GroupStudentListView(ListView):
    """
    View для списка студентов, относящихся к какой-либо группе.
    """
    paginate_by = 6
    model = AdvancedUser
    template_name = "accounts/group-student-list.html"
    context_object_name = "student_info"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        group = StudyGroup.objects.filter(id=self.kwargs['pk']).first().name
        context['title'] = f'Ученики группы {group}'
        context['heading'] = f'Ученики группы {group}'
        return context

    def get_queryset(self):
        return AdvancedUser.objects.filter(group_id=self.kwargs['pk'])


class StudentResultListView(ListView):
    """
    View для просмотра всех результатов тестирования для определённого ученика.
    """
    paginate_by = 6
    model = Result
    template_name = "accounts/student-result.html"
    context_object_name = "result_info"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        student = AdvancedUser.objects.filter(id=self.kwargs['pk']).first()
        context['title'] = f'{student.last_name} {student.first_name}'
        context['heading'] = f'{student.last_name} {student.first_name}'
        return context

    def get_queryset(self):
        return Result.objects.filter(student_id=self.kwargs['pk'])

server/accounts/templates/accounts/group-delete.html
{% extends 'main/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<h2>{{ heading }}</h2>
<form method="post">
    {% csrf_token %}
    <p>Вы действительно хотите удалить группу: <br> "{{ object.name }}" ?</p>
    <div class="mb-3">
        <button type="submit" class="btn btn-danger">Удалить</button>
        <button type="button" class="btn btn-outline-primary">
            <a href="{% url 'accounts:group_list' %}">Отмена</a>
        </button>
    </div>
</form>
{% endblock content %}

server/accounts/templates/accounts/group-list.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<h2> {{ heading }}</h2>
<table class="table table-striped table-hover" style="text-align: center; margin-top: 35px;">
    <thead>
    <tr>
        <th scope="col">Название группы</th>
        <th scope="col">
            <button type="button" class="btn btn-outline-primary"
                    onclick="window.location.href='{% url 'accounts:create_group' %}'">
                Добавить группу
            </button>
        </th>
    </tr>
    </thead>
    <tbody>
    {% for el in group_info %}
    <tr>
        <td><a href="{% url 'accounts:group_student_list' pk=el.pk %}">{{ el.name }}</a></td>
        <!-- Icons -->
        <td><a href="{% url 'accounts:update_group' pk=el.pk %}" class="fas fa-pen-square fa-2x"></a>
        <a href="{% url 'accounts:delete_group' pk=el.pk %}" class="fas fa-backspace fa-2x"></a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

server/accounts/templates/accounts/group-student-list.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<h2> {{ heading }}</h2>
<table class="table table-striped table-hover" style="text-align: center; margin-top: 35px;">
    <thead>
    <tr>
        <th scope="col">Фамилия</th>
        <th scope="col">Имя</th>
        <th scope="col">Отчество</th>
        <th scope="col">Логин</th>
        <th scope="col">
        </th>
    </tr>
    </thead>
    <tbody>
    {% for el in student_info %}
    <tr>
        <td>{{ el.last_name }}</td>
        <td>{{ el.first_name }}</td>
        <td>{{ el.patronymic }}</td>
        <td>{{ el.username }}</td>
        <!-- Icons -->
<!--        <td><a href="" class="fas fa-pen-square fa-2x"></a></td>-->
        <td>
            <button type="button" class="btn btn-outline-primary"
                    onclick="window.location.href='{% url 'accounts:student_result_list' pk=el.pk %}'">
                Успеваемость
            </button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

server/accounts/templates/accounts/profile.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<h2>Профиль {{ user.username }}</h2>
<div class="main_center">
    <div class="about_left col" style="margin-right: 4rem">
        <img src='{% static "main/images/insurance-default-image.jpg" %}'
             style="width: 20rem; height: 20rem; border-radius: 50%; display: block">
    </div>
    <div class="about_right">
        <div class="profile_info">

            <div class="list-group">
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="list-h5">Логин: {{ user_info.username }}</h5>
                    </div>
                </div>
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="list-h5">Имя: {{ user_info.first_name }}</h5>
                    </div>
                </div>
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="list-h5">Фамилия: {{ user_info.last_name }}</h5>
                    </div>
                </div>
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="list-h5">Отчество: {{ user_info.patronymic }}</h5>
                    </div>
                </div>
                 <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="list-h5">Email: {{ user_info.email }}</h5>
                    </div>
                </div>
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="btn-group d-flex w-100 justify-content-center">
<!--                        <button-->
<!--                                type="button"-->
<!--                                class="btn btn-outline-primary justify-content-center d-flex col-6"-->
<!--                                onclick=""-->
<!--                        >-->
<!--                            Редактировать профиль-->
<!--                        </button>-->
                        <button
                                type="button"
                                class="btn btn-outline-success justify-content-center d-flex col-6" style="padding: 1em 0"
                                onclick="window.location.href='{% url 'accounts:student_result_list' pk=user.id %}'"
                        >
                            Успеваемость
                        </button>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

<h3>О пользователе:</h3>
<p class="about_justify">{{ user_info.about_user }}</p>
{% endblock %}

server/accounts/templates/accounts/student-result.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<h2> {{ heading }}</h2>
<table class="table table-striped table-hover" style="text-align: center; margin-top: 35px;">
    <thead>
    <tr>
        <th scope="col">Дата прохождения</th>
        <th scope="col">Результат</th>
        <th scope="col">Тест</th>
    </tr>
    </thead>
    <tbody>
    {% for el in result_info %}
    <tr>
        <td>{{ el.appearance_date }}</td>
        <td>{{ el.result_value }}</td>
        <td><a href="{% url 'main:about_test' pk=el.test_id.pk %}">{{ el.test_id }}</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}