server/accounts/urls.py
from django.urls import path
from .views import ProfileListView, LoginView, RegisterUserCreateView, StudyGroupListView, StudyGroupCreateView, \
    StudyGroupUpdateView, StudyGroupDeleteView, GroupStudentListView, StudentResultListView, ProfileUpdateView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('profile/', ProfileListView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update_profile'),

    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterUserCreateView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='main:home'), name='logout'),

    path('group/list/', StudyGroupListView.as_view(), name='group_list'),
    path('group/create/', StudyGroupCreateView.as_view(), name='create_group'),
    path('group/<slug:pk>/update/', StudyGroupUpdateView.as_view(), name='update_group'),
    path('group/<slug:pk>/delete/', StudyGroupDeleteView.as_view(), name='delete_group'),
    path('group/<slug:pk>/student/list/', GroupStudentListView.as_view(), name='group_student_list'),

    path('student/<slug:pk>/result/list/', StudentResultListView.as_view(), name='student_result_list'),


]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/main/urls.py
from django.urls import path
from .views import TestCreateView, TestListView, QuestionListView, QuestionCreateView, QuestionUpdateView, \
    QuestionDeleteView, TestDetailView, TestUpdateView, TestDeleteView, PassingTestView, ResultDetailView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    #  Main Page
    path('', TestListView.as_view(), name='home'),
    #  Test CRUD Urls
    path('test/create/', TestCreateView.as_view(), name='create_test'),
    path('test/<slug:pk>/update/', TestUpdateView.as_view(), name='update_test'),
    path('test/<slug:pk>/delete/', TestDeleteView.as_view(), name='delete_test'),
    path('test/<slug:pk>/about/', TestDetailView.as_view(), name='about_test'),
    path('test/<slug:pk>/pass/', PassingTestView.as_view(), name='pass_test'),
    path('result/<slug:pk>/info/', ResultDetailView.as_view(), name='test_result'),
    #  Question Urls
    path('test/<slug:test_id>/quest/list/', QuestionListView.as_view(), name='quest_list'),
    path('test/<slug:test_id>/quest/create/', QuestionCreateView.as_view(), name='create_quest'),
    path('test/<slug:test_id>/quest/<slug:pk>/update/', QuestionUpdateView.as_view(), name='update_quest'),
    path('test/<slug:test_id>/quest/<slug:pk>/delete/', QuestionDeleteView.as_view(), name='delete_quest'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/main/models.py
from django.db import models
import django.utils.timezone
from accounts.models import AdvancedUser, StudyGroup


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Test(BaseModel):
    theme = models.CharField(max_length=100, verbose_name='Тема')
    name = models.CharField(max_length=100, verbose_name='Название')
    author_id = models.ForeignKey(AdvancedUser, on_delete=models.SET_NULL, null=True, max_length=100,
                                  verbose_name='Автор')
    appearance_date = models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата появления")
    hide_test = models.BooleanField(default=False, blank=True, verbose_name='Скрыть тест')
    image = models.ImageField(null=True, blank=True, verbose_name='Фотография теста')
    group_id = models.ManyToManyField(StudyGroup, blank=True, verbose_name='Для следующих учебных групп')

    class Meta:
        verbose_name_plural = 'Тесты'
        verbose_name = 'Тест'
        ordering = ['id']

    def __str__(self):
        return f'{self.name}'


class Question(BaseModel):
    info = models.CharField(max_length=255, verbose_name='Содержание')
    test_id = models.ForeignKey(Test, on_delete=models.CASCADE, verbose_name="Тест")
    variant_1 = models.CharField(max_length=255, verbose_name='Вариант №1')
    variant_2 = models.CharField(max_length=255, verbose_name='Вариант №2')
    variant_3 = models.CharField(max_length=255, verbose_name='Вариант №3')
    variant_4 = models.CharField(max_length=255, verbose_name='Вариант №4')
    variant_1_is_correct = models.BooleanField(default=False, verbose_name='Варинат №1 корректен')
    variant_2_is_correct = models.BooleanField(default=False, verbose_name='Варинат №2 корректен')
    variant_3_is_correct = models.BooleanField(default=False, verbose_name='Варинат №3 корректен')
    variant_4_is_correct = models.BooleanField(default=False, verbose_name='Варинат №4 корректен')

    class Meta:
        verbose_name_plural = 'Вопросы'
        verbose_name = 'Вопрос'
        ordering = ['id']

    def __str__(self):
        return f'Тест: {self.test_id} ID вопроса: {self.pk}'


class Result(BaseModel):
    appearance_date = models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата появления")
    test_id = models.ForeignKey(Test, on_delete=models.CASCADE, verbose_name="Тест")
    student_id = models.ForeignKey(AdvancedUser, on_delete=models.CASCADE, verbose_name="Студент")
    result_value = models.FloatField(blank=True, null=True, verbose_name='Результат')

    class Meta:
        verbose_name_plural = 'Попытки прохождения'
        verbose_name = 'Попытка прохождения'
        ordering = ['id']

    def __str__(self):
        return f'Студент: {self.student_id} / Время: {self.appearance_date}'

server/main/forms.py
from django import forms
from .models import Test, Question


class TestFilterForm(forms.Form):
    """
    Форма для фильтрации полей модели 'Product'.
    """
    name = forms.CharField(label="Название", required=False, widget=forms.TextInput(attrs={
        'class': 'col form-control', 'placeholder': 'Название'
    }))
    theme = forms.CharField(label="Тема", required=False, widget=forms.TextInput(attrs={
        'class': 'col form-control', 'placeholder': 'Тема'
    }))
    # author = forms.CharField(label="Автор", required=False, widget=forms.TextInput(attrs={
    #     'class': 'col form-control', 'placeholder': 'Автор'
    # }))


class TestModelForm(forms.ModelForm):
    """
    Форма для CRUD-операция с моделью Test.
    """

    class Meta:
        model = Test
        fields = '__all__'


class QuestionModelForm(forms.ModelForm):
    """
    Форма для CRUD-операция с моделью Question.
    """

    class Meta:
        model = Question
        fields = '__all__'


class PassingTestForm(forms.Form):
    """
    Форма для прохождения теста.
    """

    def __init__(self, *args, **kwargs):
        questions = kwargs.pop('questions')
        super(PassingTestForm, self).__init__(*args, **kwargs)
        index = 1
        label_index = 0
        for question in questions:
            if (index - 1) % 4 == 0:
                self.fields[f'label_{label_index}'] = forms.BooleanField(
                    required=False,
                    initial=False,
                    label=question.info,
                    # label_tag='13245234',
                    widget=forms.CheckboxInput(attrs={
                        'class': 'invisible_input',
                    })
                )
                label_index += 1

            self.fields[str(index)] = forms.BooleanField(
                required=False,
                initial=False,
                widget=forms.CheckboxInput(attrs={
                    'class': 'visible__input'
                }),
                label=question.variant_1)
            self.fields[str(index + 1)] = forms.BooleanField(
                required=False,
                initial=False,
                widget=forms.CheckboxInput(attrs={
                    'class': 'visible__input'
                }),
                label=question.variant_2)
            self.fields[str(index + 2)] = forms.BooleanField(
                required=False,
                initial=False,
                widget=forms.CheckboxInput(attrs={
                    'class': 'visible__input'
                }),
                label=question.variant_3)
            self.fields[str(index + 3)] = forms.BooleanField(
                required=False,
                initial=False,
                widget=forms.CheckboxInput(attrs={
                    'class': 'visible__input'
                }),
                label=question.variant_4)
            index += 4

server/main/views.py
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView, View
from .models import Test, Question, Result
from accounts.models import AdvancedUser
from .forms import TestModelForm, QuestionModelForm, PassingTestForm, TestFilterForm
from .services import TestResultService, TestFilterService
from django.http import Http404
from django.forms import formset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@method_decorator(login_required, name='dispatch')
class PassingTestView(View):
    """
    View для прохождения теста.
    """
    template_name = 'main/test-pass-form.html'

    def __init__(self, *args, **kwargs):
        super(PassingTestView, self).__init__(*args, **kwargs)

    def get_object(self):
        try:
            obj = Test.objects.get(pk=self.kwargs['pk'])
        except Exception:
            raise Http404('Тест не найден!')
        return obj

    def get_context_data(self, **kwargs):
        kwargs['test'] = self.get_object()
        kwargs['title'] = f'Тест {kwargs["test"].name}'
        kwargs['heading'] = f'Тест {kwargs["test"].name}'
        new_questions = Question.objects.filter(test_id=self.get_object())
        if 'form' not in kwargs:
            kwargs['form'] = PassingTestForm(questions=new_questions)
        return kwargs

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request, *args, **kwargs):
        new_questions = Question.objects.filter(test_id=self.get_object())
        form = PassingTestForm(request.POST, questions=new_questions)

        if form.is_valid():
            new_result = Result(
                test_id=self.get_object(),
                student_id=AdvancedUser.objects.get(pk=self.request.user.id),
                result_value=TestResultService(form, new_questions).get_result()
            )
            new_result.save()
            return redirect('main:test_result', pk=new_result.pk)
        context = {
            'form': form
        }
        return render(request, self.template_name, self.get_context_data(**context))


@method_decorator(login_required, name='dispatch')
class ResultDetailView(DetailView):
    model = Result
    query_pk_and_slug = True
    template_name = 'main/test-result.html'
    context_object_name = 'result_info'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Результат тестирования'
        context['heading'] = 'Результат тестирования'
        context['user_info'] = AdvancedUser.objects.get(pk=self.object.student_id.id)
        return context


class TestListView(ListView):
    """
    View для отображения списка тестов.
    """
    paginate_by = 6
    model = Test
    template_name = "main/index.html"
    context_object_name = "test_info"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TestFilterForm(self.request.GET)
        context['title'] = 'Все тесты'
        context['heading'] = 'Все тесты'
        return context

    def get_queryset(self):
        return TestFilterService(TestFilterForm(self.request.GET)).get_filtered_fields()
        # return Test.objects.filter(hide_test=False)


class TestDetailView(DetailView):
    """
    View для просмотра информации о тесте.
    """
    model = Test
    template_name = 'main/test-info.html'
    context_object_name = "test_info"
    query_pk_and_slug = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Тест'
        context['heading'] = 'Тест'
        return context


@method_decorator(login_required, name='dispatch')
class TestCreateView(CreateView):
    """
    View для создания теста.
    """
    model = Test
    template_name = 'main/form-template.html'
    form_class = TestModelForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создать тест'
        context['heading'] = 'Создать тест'
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('main:quest_list', kwargs={'test_id': self.object.id})


@method_decorator(login_required, name='dispatch')
class TestUpdateView(UpdateView):
    """
    View для обновления информации о тесте.
    """
    model = Test
    template_name = 'main/form-template.html'
    form_class = TestModelForm
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Обновить тест'
        context['heading'] = 'Обновить тест'
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('main:about_test', kwargs={'pk': self.object.id})


@method_decorator(login_required, name='dispatch')
class TestDeleteView(DeleteView):
    """
    View для удаления теста.
    """
    model = Test
    template_name = 'main/test-delete.html'
    query_pk_and_slug = True
    context_object_name = "test_info"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удалить тест'
        context['heading'] = 'Удалить тест'
        return context

    def get_success_url(self):
        return reverse_lazy('main:home')


@method_decorator(login_required, name='dispatch')
class QuestionListView(ListView):
    """
    View для отображения списка вопросов для определённого теста.
    """
    paginate_by = 6
    model = Question
    template_name = 'main/question-list.html'
    context_object_name = "quest_info"
    query_pk_and_slug = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Все вопросы'
        context['heading'] = 'Все вопросы'
        context['test_id'] = self.kwargs['test_id']
        return context

    def get_queryset(self):
        return Question.objects.filter(test_id=self.kwargs['test_id'])


@method_decorator(login_required, name='dispatch')
class QuestionCreateView(CreateView):
    """
    View для создания вопроса, принадлижащего к определённому тесту.
    """
    model = Question
    template_name = 'main/form-template.html'
    form_class = QuestionModelForm
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создать вопрос'
        context['heading'] = 'Создать вопрос'
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('main:quest_list', kwargs={'test_id': self.kwargs['test_id']})


@method_decorator(login_required, name='dispatch')
class QuestionUpdateView(UpdateView):
    """
    View для обновления вопроса, принадлижащего к определённому тесту.
    """
    model = Question
    template_name = 'main/form-template.html'
    form_class = QuestionModelForm
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Обновить вопрос'
        context['heading'] = 'Обновить вопрос'
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('main:quest_list', kwargs={'test_id': self.kwargs['test_id']})


@method_decorator(login_required, name='dispatch')
class QuestionDeleteView(DeleteView):
    """
    View для удаления вопроса, принадлижащего к определённому тесту.
    """
    model = Question
    template_name = 'main/question-delete.html'
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удалить вопрос'
        context['heading'] = 'Удаление вопроса'
        context['test_id'] = self.kwargs['test_id']
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('main:quest_list', kwargs={'test_id': self.kwargs['test_id']})

server/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,
          shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/all.css' %}"/>
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}"/>
    <link rel="shortcut icon" href="{% static 'main/images/python.ico' %}" type="image/x-icon">
</head>
<body>
<div class="page">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand " href="{% url 'main:home' %}" style="color: white"><span
                        style="color: aqua">ULSTU</span> Quiz</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:home' %}">Все тесты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:create_test' %}">Создать тест</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:group_list' %}">Все группы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">Все ученики</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
                                {% if not user.is_authenticated %}
                                <a class="dropdown-item" href="{% url 'accounts:login' %}">Войти</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'accounts:register' %}">Зарегистрироваться</a>
                                {% endif %}
                                {% if user.is_authenticated %}
                                <a class="dropdown-item" href="{% url 'accounts:profile' %}">Профиль</a>
                                <a class="dropdown-item" href="{% url 'accounts:update_profile' %}">Изменить профиль</a>
                                {% endif %}
                                {% if user.is_staff %}
                                <a class="dropdown-item" href="{% url 'admin:index' %}">Админ панель</a>
                                {% endif %}
                                {% if user.is_authenticated %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Выйти</a>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="main_welcome">
        {% block content %}{% endblock %}
        {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation example" class="main_pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?{{ request.GET.urlencode }}&page=1">&laquo;</a></li>
                <li class="page-item"><a class="page-link"
                                         href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}">Назад</a>
                </li>
                {% endif %}

                <span class="current">
            <li class="page-item"><a
                    class="page-link">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</a></li>
        </span>

                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">Дальше</a>
                </li>
                <li class="page-item"><a class="page-link"
                                         href="?{{ request.GET.urlencode }}&page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
    <div class="footer">
        <p class="copyright" style="margin-bottom: 0; text-align: center;">&copy;ULSTU Quiz</p>
        <p>Техподдержка: our.support@gmail.com</p>
    </div>
</div>
<script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

server/main/templates/main/delete-question.html
{% extends 'main/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<h2>{{ heading }}</h2>
<form method="post">
    {% csrf_token %}
    <p>Вы действительно хотите удалить вопрос: <br> "{{ object.info }}" ?</p>
    <div class="mb-3">
        <button type="submit" class="btn btn-danger">Удалить</button>
        <button type="button" class="btn btn-outline-primary"><a
                href="{% url 'main:quest_list' test_id=test_id %}">Отмена</a>
        </button>
    </div>
</form>
{% endblock content %}

server/main/templates/main/question-list.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<h2> {{ heading }} теста «Название теста»</h2> <!-- Добавить название теста, иначе можно запутатся. -->
<table class="table table-striped table-hover" style="text-align: center; margin-top: 35px;">
    <thead>
    <tr>
        <th scope="col" class="col-8">Вопрос</th>
        <th scope="col" class="col-4">
            <button type="button" class="btn btn-outline-primary"
                    onclick="window.location.href='{% url 'main:create_quest' test_id=test_id %}'">
                Добавить вопрос
            </button>
        </th>
    </tr>
    </thead>
    <tbody>
    {% for el in quest_info %}
    <tr>
        <td>{{ el.info }}</td>
        <!-- Icons -->
        <td><a href="{% url 'main:update_quest' test_id=test_id pk=el.pk %}" class="fas fa-pen-square fa-2x"></a>
        <a href="{% url 'main:delete_quest' test_id=test_id pk=el.pk %}" class="fas fa-backspace fa-2x"></a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

server/main/templates/main/test-info.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<h2>{{ heading }} <a href="{% url 'main:quest_list' test_id=test_info.pk %}">«{{ test_info.name }}»</a></h2>
<div class="main_center">
    <div class="about_left col" style="margin-right: 4rem">
        <img src='{% static "main/images/insurance-default-image.jpg" %}'
             style="width: 20rem; height: 20rem; border-radius: 50%; display: block">
    </div>
    <div class="about_right">
        <div class="profile_info">

            <div class="list-group">
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="list-h5">Тема: {{ test_info.theme }}</h5>
                    </div>
                </div>
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="list-h5">Название: {{ test_info.name }}</h5>
                    </div>
                </div>
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="list-h5">Автор: {{ test_info.author_id }}</h5>
                    </div>
                </div>
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="list-h5">Дата создания: {{ test_info.appearance_date }}</h5>
                    </div>
                </div>
<!--                <div class="list-group-item list-group-item-action" aria-current="true">-->
<!--                    <div class="d-flex w-100 justify-content-between">-->
<!--                        <button type="button" class="btn btn-outline-success justify-content-between d-flex btn-lg" style="-->
<!--margin-top: 20px; margin: 0 auto;" onclick="window.location.href='{% url 'main:quest_list' test_id=test_info.pk %}'">-->
<!--                            Список вопросов-->
<!--                        </button>-->
<!--                    </div>-->
<!--                </div>-->
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="btn-group btn-group-lg col-12 mx-auto" role="group" aria-label="buttons">
                        <button type="button" class="btn btn-outline-primary justify-content-between d-flex" style="
margin-top: 20px; margin: 0 auto; text-align: center" onclick="window.location.href='{% url 'main:update_test' pk=test_info.pk %}'">
                            Редактировать тест
                        </button>
                        <button type="button" class="btn btn-outline-danger justify-content-between d-flex" style="
margin-top: 20px; margin: 0 auto; text-align: center" onclick="window.location.href='{% url 'main:delete_test' pk=test_info.pk %}'">
                            Удалить тест
                        </button>
                    </div>
                </div>
                <div class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <button
                                type="button"
                                class="btn btn-outline-success justify-content-between d-flex btn-lg"
                                style="
margin-top: 20px; margin: 0 auto;"
                                onclick="window.location.href='{% url 'main:pass_test' pk=test_info.pk %}'"
                        >
                            Пройти тест
                        </button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<h3>О тесте:</h3>
<p class="about_justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
{% endblock %}

server/main/templates/main/test-result.html
{% extends 'main/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<h2 style="margin-bottom: 2em;">{{ heading }}</h2>
<p class="p_center form_margin">Был пройден тест «{{ result_info.test_id }}»</p>
<p class="p_center form_margin">Тема: {{ result_info.test_id.theme }}</p>
<p class="p_center form_margin">Студент: {{ user_info.last_name }} {{ user_info.first_name }} {{ user_info.patronymic }}</p>
<p class="p_center form_margin">Группа: {{ user_info.group_id}}</p>
<p class="p_center form_margin">Результат: {{ result_info.result_value }}</p>
<div class="d-grid gap-2 d-md-flex justify-content-center border-top" style="padding: 1rem 0">
    <button
            type="button"
            class="btn btn-outline-success"
            onclick="window.location.href='{% url 'accounts:student_result_list' pk=user_info.id %}'"
    >Перейти к общим результатам
    </button>
    <button
            type="button"
            class="btn btn-outline-primary"
            onclick="window.location.href='{% url 'main:home' %}'"
    >На главную</button>
</div>
{% endblock content %}